### ISSUE TITLE
Error in refseq download

### ISSUE THREAD

**Issue by bgyori** [indralab/protmapper#9]
```
======================================================================
ERROR: test_uniprot_client.test_get_ids_from_refseq
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/build/indralab/protmapper/protmapper/tests/test_uniprot_client.py", line 186, in test_get_ids_from_refseq
    up_ids = uniprot_client.get_ids_from_refseq('NP_003395.1')
  File "/home/travis/build/indralab/protmapper/protmapper/uniprot_client.py", line 689, in get_ids_from_refseq
    up_ids = um.refseq_uniprot[refseq_id]
  File "/home/travis/build/indralab/protmapper/protmapper/uniprot_client.py", line 812, in refseq_uniprot
    self.initialize_refseq()
  File "/home/travis/build/indralab/protmapper/protmapper/uniprot_client.py", line 728, in initialize_refseq
    self._refseq_uniprot = _build_refseq_uniprot()
  File "/home/travis/build/indralab/protmapper/protmapper/uniprot_client.py", line 940, in _build_refseq_uniprot
    'refseq_uniprot')
  File "/home/travis/build/indralab/protmapper/protmapper/resources.py", line 286, in get_create_resource_file
    self.download_resource_file(resource_id, cached)
  File "/home/travis/build/indralab/protmapper/protmapper/resources.py", line 264, in download_resource_file
    download_fun(fname, cached=cached)
  File "/home/travis/build/indralab/protmapper/protmapper/resources.py", line 159, in download_refseq_uniprot
    _download_from_s3('refseq_uniprot.csv')
TypeError: _download_from_s3() missing 1 required positional argument: 'out_file'
-------------------- >> begin captured logging << --------------------
protmapper.resources: INFO: Could not access 'refseq_uniprot' resource file, will download.
protmapper.resources: INFO: Downloading 'refseq_uniprot' resource file into /home/travis/.protmapper/refseq_uniprot.csv from cache.
--------------------- >> end captured logging << ---------------------
```

**Comment by bgyori** [comment]
Fixed in #10
